spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
      #sql:
      # init:
      # mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 or PostgreSQL

    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect

    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    #For PostgreSQL
    #database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
      format_sql: true
    defer-datasource-initialization: true
#Cloudinary Properties
cloudinary:
  api-key: 214881779555371
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: unamoregrande

server.port: ${PORT:8080}